{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "depkon-operator.helmLabels" . | indent 4 }}
  name: {{ template "depkon-operator.fullname" . }}-cluster-role
rules:
- apiGroups:
  - akankshakumari393.dev
  resources:
  - depkons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - update
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - akankshakumari393.dev
  resources:
  - depkons/status
  verbs:
  - update
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "depkon-operator.helmLabels" . | indent 4 }}
  name: {{ template "depkon-operator.fullname" . }}-cr-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "depkon-operator.fullname" . }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ template "depkon-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
---
