{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "convalkontroller.labels" . | nindent 4 }}
  name: {{ template "convalkontroller.fullname" . }}-cluster-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "convalkontroller.labels" . | nindent 4 }}
  name: {{ template "convalkontroller.fullname" . }}-cr-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "convalkontroller.fullname" . }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ template "convalkontroller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
---